# Generated by Django 3.0.5 on 2020-04-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default='No news'),
        ),
        migrations.AddField(
            model_name='news',
            name='posted_date',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
    ]
