# Generated by Django 3.0.5 on 2020-05-08 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_auto_20200508_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='from_user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
