# Generated by Django 3.0.5 on 2020-05-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200508_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='not_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
