# Generated by Django 3.0.5 on 2020-05-08 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0028_auto_20200508_0024'),
        ('notification', '0005_notificationtype_not_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_challenge',
            field=models.ForeignKey(blank=True, default=159, on_delete=django.db.models.deletion.CASCADE, related_name='notification_challenge', to='challenges.Challenge'),
        ),
    ]
