# Generated by Django 3.0.5 on 2020-05-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20200508_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_challenge',
        ),
    ]
