# Generated by Django 3.0.5 on 2020-04-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('topic', models.CharField(help_text='Please choose a topic for you challenge (Education, Law, Science, Medicine, IT, etc.)', max_length=30)),
                ('short_description', models.CharField(help_text='Please provide a short description of the challenge.', max_length=500)),
                ('number_of_checks', models.IntegerField(help_text='How many reviews do you want this challenge to go through?')),
                ('level', models.CharField(blank=True, max_length=30)),
                ('deadline', models.DateField(help_text='Please provide a deadline for the reviews.')),
                ('challenge_text', models.TextField()),
                ('notes', models.TextField(blank=True, help_text='Leave any additional comments here.')),
            ],
        ),
    ]
