# Generated by Django 3.0.5 on 2020-04-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
