# Generated by Django 3.0.5 on 2020-04-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='date_created',
            new_name='start_date',
        ),
    ]
