# Generated by Django 3.0.5 on 2020-04-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed_number_of_checks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='number_of_checks',
            field=models.IntegerField(default=0, help_text='How many reviews do you want this challenge to go through?'),
        ),
    ]
