# Generated by Django 3.0.5 on 2020-04-19 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0009_mychallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mychallenge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mychallenge',
            name='challenge',
            field=models.ManyToManyField(default='Null', to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='mychallenge',
            name='text_before_review',
            field=models.TextField(default='Null'),
        ),
    ]
