# Generated by Django 3.0.5 on 2020-04-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0011_auto_20200419_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychallenge',
            name='challenge',
            field=models.ManyToManyField(blank=True, to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='mychallenge',
            name='text_before_review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mychallenge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
