# Generated by Django 3.0.5 on 2020-04-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20200419_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyChallenge',
        ),
    ]
