# Generated by Django 3.0.5 on 2020-04-19 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0013_delete_mychallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateField(auto_now=True)),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('text_before_review', models.TextField(blank=True)),
                ('text_after_review', models.TextField(blank=True)),
                ('challenge', models.ManyToManyField(blank=True, to='challenges.Challenge')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
