# Generated by Django 3.0.5 on 2020-04-19 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_mychallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='date_accepted',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='challenge',
            name='date_completed',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='challenge',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='MyChallenge',
        ),
    ]
