# Generated by Django 3.0.5 on 2020-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_auto_20200419_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='agreed_number_of_checks',
            field=models.IntegerField(default=0),
        ),
    ]
