# Generated by Django 3.0.5 on 2020-04-19 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0016_challenge_agreed_number_of_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_starter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_starter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='peer_reviewer',
            field=models.ManyToManyField(blank=True, related_name='peer_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
