# Generated by Django 3.0.5 on 2020-04-20 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0017_auto_20200419_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed_peer_reviewer',
            field=models.ManyToManyField(blank=True, related_name='completed_peer_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
