# Generated by Django 3.0.5 on 2020-05-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0020_challenge_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
