# Generated by Django 3.0.5 on 2020-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0021_auto_20200505_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
