# Generated by Django 3.0.5 on 2020-05-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0022_challenge_challenge_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='challenge_file',
        ),
    ]
