# Generated by Django 3.0.5 on 2020-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0023_remove_challenge_challenge_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='file_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='result_file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
