# Generated by Django 3.0.5 on 2020-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0025_auto_20200505_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed_other_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='agreed_number_of_checks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='completed_number_of_checks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='number_of_checks',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many reviews do you want this challenge to go through?'),
        ),
    ]
