# Generated by Django 3.0.5 on 2020-05-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0026_auto_20200507_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTopicName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='topic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='topic', to='challenges.ChallengeTopicName'),
        ),
    ]
