# Generated by Django 3.0.5 on 2020-05-09 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0028_auto_20200508_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_starter',
            field=models.ForeignKey(blank=True, default=27, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_starter', to=settings.AUTH_USER_MODEL),
        ),
    ]
