# Generated by Django 3.0.5 on 2020-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0029_auto_20200509_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='short_description',
            field=models.TextField(help_text='Please provide a short description of the challenge.'),
        ),
    ]
