# Generated by Django 3.0.5 on 2020-05-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20200418_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='fifty_challenges',
            new_name='completed_fifty_challenges',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='five_challenges',
            new_name='completed_five_challenges',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='one_challenge',
            new_name='completed_one_challenge',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='one_hundred_challenges',
            new_name='completed_one_hundred_challenges',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='one_month_streak',
            new_name='completed_twenty_challenges',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='seven_days_streak',
            new_name='started_fifty_challenges',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='twenty_challenges',
            new_name='started_five_challenges',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='two_day_streak',
            new_name='started_one_challenge',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='two_weeks_streak',
            new_name='started_one_hundred_challenges',
        ),
        migrations.AddField(
            model_name='badge',
            name='started_twenty_challenges',
            field=models.BooleanField(default=False),
        ),
    ]
